=== y-dada-dev/ESI-SBA-CSI-Web-Languages-And-Tools-TP03/Solution/Solution B/bouteille.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  
  <!-- Déclarations de éléments simples -->
  <xs:element name="ph" type="T_PH"/> 
  <xs:element name="marque" type="xs:string"/>
  <xs:element name="commune" type="xs:string"/>
  <xs:element name="wilaya" type="xs:string"/>
  <xs:element name="code_barre" type="Tcodebar"/>  
  <xs:element name="contenance" type="Tcontenance"></xs:element>
   
  <!-- Déclarations de types simples -->
  
  <xs:simpleType name="T_PH">
    <xs:restriction base="xs:decimal">
      <xs:maxInclusive value="8.5"></xs:maxInclusive>
      <xs:minInclusive value="6.5"></xs:minInclusive>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Tunit">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Mg/l"></xs:enumeration>
      <xs:enumeration value="g/l"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Tcodebar">
    <xs:restriction base="xs:positiveInteger">
      <xs:totalDigits value="14"></xs:totalDigits>
    </xs:restriction>
  </xs:simpleType>  
  <xs:complexType name="Tcontenance">
    <xs:simpleContent>
      <xs:extension base="xs:integer">
        <xs:attribute name="unit" use="required" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>   
  </xs:complexType>
  
  <!-- Déclarations des éléments complexes -->
  <xs:element name="bouteille">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="marque"/>
        <xs:element ref="composition"/>
        <xs:element ref="source"/>
        <xs:element ref="code_barre"/>
        <xs:element ref="contenance"/>
        <xs:element ref="ph"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
 <xs:element name="composition">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ion_positif"/>
        <xs:element ref="ion_negatif"/>
        <xs:element minOccurs="0" ref="autre"/>
      </xs:sequence>
      <xs:attribute name="unit" use="required" type="Tunit"/>
    </xs:complexType>
  </xs:element> 
  <xs:element name="ion_positif">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="ion"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element> 
  <xs:element name="ion_negatif">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="ion"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="autre">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="type" use="required" type="xs:string"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="source">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="commune"/>
        <xs:element ref="wilaya"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ion">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="quantité" use="required" type="xs:decimal"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <!--Root--> 
  <xs:element name="bouteilles">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="bouteille"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== y-dada-dev/ESI-SBA-CSI-Web-Languages-And-Tools-TP03/Solution/Solution B/bouteille.xml
<?xml version="1.0" encoding="UTF-8"?>
<bouteilles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="bouteille.xsd">
    <bouteille>
        <marque>Ifri</marque>
        <composition unit="Mg/l">
            <ion_positif>
                <ion quantité="71">calcium </ion>
                <ion quantité="5.5">magnésium </ion>
            </ion_positif>
            <ion_negatif>
                <ion quantité="20">chlorure </ion>
                <ion quantité="1">nitrate </ion>
            </ion_negatif>
            <autre type="metal">fer</autre>
        </composition>
        <source>
            <commune>Ifri</commune>
            <wilaya>Bejaia</wilaya>
        </source>
        <code_barre>3274080005003</code_barre>
        <contenance unit="cl">150</contenance>
        <ph>7.45</ph>
    </bouteille>
    <bouteille>
        <marque> Guedila</marque>
        <composition unit="Mg/l">
            
            <ion_positif>
                <ion quantité="81">calcium </ion>
                <ion quantité="4">magnésium </ion>
            </ion_positif>
            <ion_negatif>
                <ion quantité="3.6">chlorure </ion>
                <ion quantité="2">nitrate </ion>
            </ion_negatif>
        </composition>
        <source>
            <commune>Djemorah</commune>
            <wilaya>Biskra</wilaya>
        </source>
        <code_barre>3268840001008</code_barre>
        <contenance unit="cl">50</contenance>
        <ph>7.5</ph>
    </bouteille>
    <bouteille>
        <marque>Saida</marque>
        <composition unit="Mg/l" >
            
            <ion_positif>
                <ion quantité="11">calcium </ion>
                <ion quantité="8">magnésium </ion>
            </ion_positif>
            <ion_negatif>
                <ion quantité="13.5">chlorure </ion>
                <ion quantité="6.3">nitrate </ion>
            </ion_negatif>
          
        </composition>
        <source>
            <commune>Ain-El-Hjar</commune>
            <wilaya>Saida</wilaya>
        </source>
        <code_barre>3057640117008</code_barre>
        <contenance unit="cl">50</contenance>
        <ph>7</ph>
    </bouteille>
    
</bouteilles>
