=== y-dada-dev/ESI-SBA-CSI-Web-Languages-And-Tools-TP03/Solution/Solution B/pays.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <!--Déclarations des éléments -->
<xsd:element name="nbr_population">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:positiveInteger">
                    <xsd:attribute name="en" type="xsd:gYear" use="required"/>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="pays">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="capitale" type="xsd:string"/>
                <xsd:element ref="nbr_population"/>
            </xsd:sequence>
            <xsd:attribute name="nom" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <!--Root-->
    <xsd:element name="annuaire">
        <xsd:complexType>
            <xsd:sequence minOccurs="1" maxOccurs="unbounded">
                <xsd:element ref="pays"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== y-dada-dev/ESI-SBA-CSI-Web-Languages-And-Tools-TP03/Solution/Solution B/pays.xml
<?xml version="1.0" encoding="UTF-8" ?>

<annuaire xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="pays.xsd">
    <pays nom="AlgÃ©rie">
        <capitale> Alger </capitale>
        <nbr_population en="2016">40378714</nbr_population>
    </pays>
    

    <pays nom="Tunisie">
        <capitale> tunis </capitale>
        <nbr_population en="2015">11191854</nbr_population>
    </pays>
    
    <pays nom="Maroc">
        <capitale> Rabat </capitale>
        <nbr_population en="2015">34149357</nbr_population>
    </pays>
    
    
    
</annuaire>
